version = 0.1

[default.global.parameters]
stack_name = "s1math-api"
region     = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
s3_bucket       = ""   # fill in after first deploy: sam deploy --guided
s3_prefix       = "s1math"
resolve_s3      = true
